---
- name: k3s systemd unitfile check
  hosts: all
  # hosts: localhost
  gather_facts: false

  tasks:
  - name: exist check k3s.service
    ansible.builtin.stat:
      path: /etc/systemd/system/k3s.service
    register: server

  - name: exist check k3s-agent.service
    ansible.builtin.stat:
      path: /etc/systemd/system/k3s-agent.service
    register: agent

  - name: print exist check result
    debug:
      msg:
      - "{{ server.stat.exists }}"
      - "{{ agent.stat.exists }}"

  - name: set path
    set_fact:
      unit_name: "{{ server.stat.exists |
                      ternary('k3s', agent.stat.exists |
                        ternary('k3s-agent', none) ) }}"

  - name: print service name
    debug:
      msg: "{{ unit_name }}"
