---
- name: k3s systemd unitfile check
  hosts: all
  # hosts: localhost
  gather_facts: false

  tasks:
  - name: exist check k3s.service
    ansible.builtin.stat:
      path: /etc/systemd/system/k3s.service
    register: stat

  - name: print exist check result
    debug:
      msg: "{{ stat.stat.exists }}"

  - name: set path
    set_fact:
      unit_name: "{{ stat.stat.exists |
                    ternary('k3s', 'k3s-agent') }}"

  - name: print service name
    debug:
      msg: "{{ unit_name }}"
